export interface LabeledOption {
  value: string;
  label: string;
}

export interface GlobalUiContent {
  loadingLabel?: string | null;
  closeLabel?: string | null;
  productFallbackName?: string | null;
  errorTitle?: string | null;
  errorMessage?: string | null;
  retryButtonLabel?: string | null;
  homeButtonLabel?: string | null;
  errorBoundaryTitle?: string | null;
  errorBoundaryMessage?: string | null;
  errorBoundaryReloadButton?: string | null;
}

export interface AuthUiContent {
  loginTitle?: string | null;
  loginSubtitle?: string | null;
  emailLabel?: string | null;
  emailPlaceholder?: string | null;
  passwordLabel?: string | null;
  passwordPlaceholder?: string | null;
  forgotPasswordLink?: string | null;
  rememberMeLabel?: string | null;
  loginButtonLabel?: string | null;
  loginSubmittingLabel?: string | null;
  loginErrorTitle?: string | null;
  loginErrorFallback?: string | null;
  loginNoAccountText?: string | null;
  loginRegisterLink?: string | null;
  registerTitle?: string | null;
  registerSubtitle?: string | null;
  registerButtonLabel?: string | null;
  registerSubmittingLabel?: string | null;
  registerSuccessTitle?: string | null;
  registerSuccessDescription?: string | null;
  registerErrorTitle?: string | null;
  registerErrorFallback?: string | null;
  registerValidationErrorTitle?: string | null;
  registerEmptyFieldsMessage?: string | null;
  registerKvkkRequiredMessage?: string | null;
  registerPasswordMinMessage?: string | null;
  registerHasAccountText?: string | null;
  registerLoginLink?: string | null;
  registerKvkkConsentText?: string | null;
  forgotTitle?: string | null;
  forgotSubtitle?: string | null;
  forgotSuccessTitle?: string | null;
  forgotSuccessSubtitle?: string | null;
  forgotBackToLogin?: string | null;
  forgotSubmitLabel?: string | null;
  forgotSubmittingLabel?: string | null;
  forgotResendLabel?: string | null;
  forgotSuccessToastTitle?: string | null;
  forgotSuccessToastDescription?: string | null;
  forgotErrorTitle?: string | null;
  forgotEmptyEmailMessage?: string | null;
  forgotErrorFallback?: string | null;
  forgotLoginPrompt?: string | null;
  forgotLoginLink?: string | null;
  resetPasswordTitle?: string | null;
  resetPasswordSuccessTitle?: string | null;
  resetPasswordSuccessDescription?: string | null;
  resetPasswordNewLabel?: string | null;
  resetPasswordConfirmLabel?: string | null;
  resetPasswordConfirmPlaceholder?: string | null;
  resetPasswordSubmitLabel?: string | null;
  resetPasswordSubmittingLabel?: string | null;
  resetPasswordChangedTitle?: string | null;
  resetPasswordChangedDescription?: string | null;
  resetPasswordLoginButton?: string | null;
  resetPasswordInvalidLinkTitle?: string | null;
  resetPasswordInvalidLinkDescription?: string | null;
  resetPasswordSuccessToastTitle?: string | null;
  resetPasswordSuccessToastDescription?: string | null;
  resetPasswordErrorTitle?: string | null;
  resetPasswordRequiredMessage?: string | null;
  resetPasswordMinLengthMessage?: string | null;
  resetPasswordMismatchMessage?: string | null;
}

export interface AccountUiContent {
  pageTitle?: string | null;
  guestNameFallback?: string | null;
  memberSincePrefix?: string | null;
  navAccount?: string | null;
  navOrders?: string | null;
  navWishlist?: string | null;
  navAddresses?: string | null;
  navPaymentMethods?: string | null;
  logoutButton?: string | null;
  ordersCardTitle?: string | null;
  ordersCardSubtitle?: string | null;
  cartCardTitle?: string | null;
  cartCardSubtitle?: string | null;
  wishlistCardTitle?: string | null;
  wishlistCardSubtitle?: string | null;
  ordersTabLabel?: string | null;
  emptyOrdersTitle?: string | null;
  emptyOrdersDescription?: string | null;
  emptyOrdersButton?: string | null;
  productUnitLabel?: string | null;
  viewOrderButton?: string | null;
  ordersLoadError?: string | null;
}

export interface CartUiContent {
  titlePrefix?: string | null;
  emptyTitle?: string | null;
  emptyDescription?: string | null;
  continueShoppingButton?: string | null;
  subtotalLabel?: string | null;
  shippingNote?: string | null;
  checkoutButton?: string | null;
  loginRequiredNote?: string | null;
  loginAndContinueButton?: string | null;
}

export interface WishlistUiContent {
  sidebarTitlePrefix?: string | null;
  sidebarEmptyTitle?: string | null;
  sidebarEmptyDescription?: string | null;
  sidebarExploreButton?: string | null;
  sidebarAddToCartLabel?: string | null;
  sidebarContinueButton?: string | null;
  pageTitle?: string | null;
  pageProductUnit?: string | null;
  pageContinueShopping?: string | null;
  pageAddAllToCart?: string | null;
  pageEmptyTitle?: string | null;
  pageEmptyDescription?: string | null;
  pageStartShopping?: string | null;
  addAllSuccessToast?: string | null;
  addAllErrorToast?: string | null;
}

export interface ShopUiContent {
  productsLoadError?: string | null;
  categoriesLoadError?: string | null;
  filtersButtonLabel?: string | null;
  clearFiltersLabel?: string | null;
  searchPlaceholder?: string | null;
  sortLabel?: string | null;
  resultsLabel?: string | null;
  emptyTitle?: string | null;
  emptyDescription?: string | null;
  loadMoreLabel?: string | null;
  loadingLabel?: string | null;
  sortOptions: LabeledOption[];
  filterCategoryTitle?: string | null;
  filterGenderTitle?: string | null;
  filterSizeTitle?: string | null;
  filterColorTitle?: string | null;
  filterPriceTitle?: string | null;
  filterFitTitle?: string | null;
  filterSleeveTitle?: string | null;
  filterNeckTitle?: string | null;
  filterMaterialTitle?: string | null;
  filterSeasonTitle?: string | null;
  filterPatternTitle?: string | null;
  filterQualityTitle?: string | null;
  genderOptions: string[];
  sizeOptions: string[];
  colorOptions: string[];
  priceRangeOptions: LabeledOption[];
  fitOptions: string[];
  sleeveOptions: string[];
  neckOptions: string[];
  materialOptions: string[];
  seasonOptions: string[];
  patternOptions: string[];
  qualityOptions: string[];
}

export interface CheckoutUiContent {
  defaultCountry?: string | null;
  validationErrorTitle?: string | null;
  validationErrorMessage?: string | null;
  selectAddressError?: string | null;
  addressTabLabel?: string | null;
  paymentTabLabel?: string | null;
  savedAddressesTitle?: string | null;
  noAddressYet?: string | null;
  defaultAddressBadge?: string | null;
  phonePrefix?: string | null;
  addAddressTitle?: string | null;
  fullNameLabel?: string | null;
  fullNamePlaceholder?: string | null;
  phoneLabel?: string | null;
  addressLabel?: string | null;
  addressPlaceholder?: string | null;
  cityLabel?: string | null;
  cityPlaceholder?: string | null;
  districtLabel?: string | null;
  districtPlaceholder?: string | null;
  districtSelectCityFirst?: string | null;
  postalCodeLabel?: string | null;
  defaultAddressCheckbox?: string | null;
  saveAddressSubmitting?: string | null;
  saveAddressButton?: string | null;
  cancelButton?: string | null;
  addAddressButton?: string | null;
  orderSummaryTitle?: string | null;
  moreItemsNote?: string | null;
  cartTotalLabel?: string | null;
  shippingFeeLabel?: string | null;
  grandTotalLabel?: string | null;
  continueToPaymentButton?: string | null;
  cities: string[];
  districtsByCity: Record<string, string[]>;
  deleteAddressConfirm?: string | null;
  contractsRequiredMessage?: string | null;
  paymentErrorTitle?: string | null;
  paymentErrorFallback?: string | null;
  orderCreateErrorFallback?: string | null;
  shippingOptionsTitle?: string | null;
  shippingLoadingLabel?: string | null;
  shippingLoadError?: string | null;
  paymentOptionsTitle?: string | null;
  paymentLoadingLabel?: string | null;
  paymentOptionsLoadError?: string | null;
  bankAccountsLoadError?: string | null;
  iyzicoPayButton?: string | null;
  iyzicoRedirectingLabel?: string | null;
  iyzicoSecurityNote?: string | null;
  bankTransferTitle?: string | null;
  bankTransferSubtitle?: string | null;
  bankTransferNote?: string | null;
  copyIbanButton?: string | null;
  createOrderBankTransferSubmitting?: string | null;
  createOrderBankTransferButton?: string | null;
  havaleInstructionsTitle?: string | null;
  orderNumberLabel?: string | null;
  goToOrdersButton?: string | null;
  alreadyHaveAccountText?: string | null;
  loginLink?: string | null;
  havaleSuccessTitle?: string | null;
  havaleSuccessDescription?: string | null;
  orderDetailLoadError?: string | null;
  orderNotFound?: string | null;
  backToAccountButton?: string | null;
  backButton?: string | null;
  orderNumberPrefix?: string | null;
  orderDatePrefix?: string | null;
  trackingNumberPrefix?: string | null;
  paymentInfoTitle?: string | null;
  statusLabel?: string | null;
  paymentMethodLabel?: string | null;
  cardLabel?: string | null;
  transactionIdLabel?: string | null;
  productsTitle?: string | null;
  quantityPrefix?: string | null;
  colorPrefix?: string | null;
  sizePrefix?: string | null;
  shippingAddressTitle?: string | null;
  subtotalLabel?: string | null;
  discountLabel?: string | null;
  taxLabel?: string | null;
  totalLabel?: string | null;
  shippingMethodTitle?: string | null;
  estimatedDeliveryPrefix?: string | null;
  completePaymentButton?: string | null;
  cancelOrderButton?: string | null;
  cancelDialogTitle?: string | null;
  cancelDialogDescription?: string | null;
  cancelReasonPlaceholder?: string | null;
  cancelDialogDismiss?: string | null;
  cancelDialogConfirm?: string | null;
  cancelDialogSubmitting?: string | null;
  paymentResultCheckingTitle?: string | null;
  paymentResultPollNote?: string | null;
  paymentResultMissingOrderTitle?: string | null;
  paymentResultMissingOrderDescription?: string | null;
  paymentResultSuccessTitle?: string | null;
  paymentResultSuccessDescription?: string | null;
  paymentResultFailedTitle?: string | null;
  paymentResultFailedDescription?: string | null;
  paymentResultRefundedTitle?: string | null;
  paymentResultRefundedDescription?: string | null;
  paymentResultPendingTitle?: string | null;
  paymentResultPendingDescription?: string | null;
  refreshButton?: string | null;
  retryPaymentButton?: string | null;
  orderDetailsTitle?: string | null;
  paymentResultFailedBanner?: string | null;
  viewOrderDetailButton?: string | null;
  continueShoppingButton?: string | null;
  orderStatusLabels: LabeledOption[];
  paymentStatusLabels: LabeledOption[];
  addressesPageTitle?: string | null;
  addressesBackNav?: string | null;
  addressesEmptyLine1?: string | null;
  addressesEmptyLine2?: string | null;
  addressesDefaultBadge?: string | null;
  addressesDeleteTitle?: string | null;
  addressesDeleteDescription?: string | null;
  addressesDeleteConfirm?: string | null;
  addressesEditTitle?: string | null;
  addressesAddTitle?: string | null;
  addressesUpdateSubmitting?: string | null;
  addressesUpdateButton?: string | null;
  paymentMethodsPageTitle?: string | null;
  paymentMethodsBackNav?: string | null;
  paymentMethodsSecurityNote?: string | null;
  paymentMethodsEmpty?: string | null;
  paymentMethodsLoadError?: string | null;
  paymentMethodsCardFallback?: string | null;
}

export interface OrdersUiContent {
  pageTitle?: string | null;
  pageSubtitle?: string | null;
  searchPlaceholder?: string | null;
  allStatusesLabel?: string | null;
  loadErrorTitle?: string | null;
  loadErrorFallback?: string | null;
  retryButton?: string | null;
  emptyFilteredTitle?: string | null;
  emptyTitle?: string | null;
  emptyFilteredDescription?: string | null;
  emptyDescription?: string | null;
  startShoppingButton?: string | null;
  productUnitLabel?: string | null;
  paymentPendingBadge?: string | null;
  totalLabel?: string | null;
  payButton?: string | null;
  detailButton?: string | null;
  previousPage?: string | null;
  nextPage?: string | null;
  pageLabel?: string | null;
  statusOptions: LabeledOption[];
}

export interface ProductUiContent {
  notFoundIdError?: string | null;
  loadError?: string | null;
  loadingLabel?: string | null;
  notFoundTitle?: string | null;
  backToShopButton?: string | null;
  categorySpecLabel?: string | null;
  stockSpecSuffix?: string | null;
  outOfStockTitle?: string | null;
  outOfStockDescription?: string | null;
  addedToCartTitle?: string | null;
  addedToCartDescription?: string | null;
  shareCopiedToast?: string | null;
  breadcrumbHome?: string | null;
  breadcrumbShop?: string | null;
  saleBadge?: string | null;
  newBadge?: string | null;
  reviewsLabel?: string | null;
  discountBadge?: string | null;
  colorLabel?: string | null;
  colorPlaceholder?: string | null;
  sizeLabel?: string | null;
  sizePlaceholder?: string | null;
  quantityLabel?: string | null;
  addToCartButton?: string | null;
  removeFromWishlistButton?: string | null;
  addToWishlistButton?: string | null;
  shareButtonTitle?: string | null;
  inStockTitle?: string | null;
  outOfStockStatusTitle?: string | null;
  stockCountLabel?: string | null;
  fastDeliveryTitle?: string | null;
  fastDeliveryDescription?: string | null;
  paymentOptionsTitle?: string | null;
  paymentOptionsDescription?: string | null;
  warrantyTitle?: string | null;
  warrantyDescription?: string | null;
  tagsSectionTitle?: string | null;
  tabDescription?: string | null;
  tabSpecs?: string | null;
  tabReviews?: string | null;
  descriptionHeading?: string | null;
  emptyDescription?: string | null;
  specsHeading?: string | null;
  emptySpecs?: string | null;
  reviewsHeading?: string | null;
  reviewsSummary?: string | null;
  writeReviewButton?: string | null;
  similarProductsTitle?: string | null;
  viewAllLink?: string | null;
  cardAddToCartButton?: string | null;
  cardAddToCartSubmitting?: string | null;
  cardAddSuccessTitle?: string | null;
  cardAddErrorToast?: string | null;
  cardWishlistAriaLabel?: string | null;
}

export interface CategoryUiContent {
  loadError?: string | null;
  allCategoriesTitle?: string | null;
  categoryProductsSubtitle?: string | null;
  allCategoriesSubtitle?: string | null;
  productsSectionTitle?: string | null;
  viewModeLabel?: string | null;
  emptyTitle?: string | null;
  emptyDescription?: string | null;
  viewAllProductsButton?: string | null;
  sectionTitle?: string | null;
  viewAllLink?: string | null;
}

export interface ContextUiContent {
  cartAddSuccessTitle?: string | null;
  cartAddErrorTitle?: string | null;
  cartAddErrorFallback?: string | null;
  cartRemoveInfoTitle?: string | null;
  cartRemoveInfoDescription?: string | null;
  cartRemoveErrorTitle?: string | null;
  cartRemoveErrorFallback?: string | null;
  cartQuantityErrorTitle?: string | null;
  cartClearSuccessTitle?: string | null;
  cartClearErrorTitle?: string | null;
  cartClearErrorFallback?: string | null;
  wishlistAlreadyInTitle?: string | null;
  wishlistAddSuccessTitle?: string | null;
  wishlistAddErrorTitle?: string | null;
  wishlistRemoveInfoTitle?: string | null;
  wishlistRemoveInfoDescription?: string | null;
  wishlistRemoveErrorTitle?: string | null;
  wishlistRemoveErrorFallback?: string | null;
}

export interface AppPagesUiContent {
  global?: GlobalUiContent | null;
  auth?: AuthUiContent | null;
  account?: AccountUiContent | null;
  cart?: CartUiContent | null;
  wishlist?: WishlistUiContent | null;
  shop?: ShopUiContent | null;
  checkout?: CheckoutUiContent | null;
  orders?: OrdersUiContent | null;
  product?: ProductUiContent | null;
  category?: CategoryUiContent | null;
  context?: ContextUiContent | null;
}
